<a href="https://colab.research.google.com/github/Erika2397/Clusterizacion-como-manejar-datos-no-etiquetados-/blob/main/notebooks/aula_2/notebook_aula_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
url = 'https://raw.githubusercontent.com/Erika2397/Clusterizacion-como-manejar-datos-no-etiquetados-/refs/heads/main/datos_mkt_traducido.csv'

# Recopilando y ajustando datos

In [3]:
df = pd.read_csv(url)
df

,sexo,edad,numero_de_amigos,basquet,futbol_americano,futbol,softbol,voleibol,natacion,animacion,...,musica,rock,cabello,vestido,centro_comercial,compras,ropa,nuestra_marca,marca_de_la_competencia,bebidas
0,F,27,49,0,0,10,0,0,10,0,...,0,0,0,0,0,0,0,0,0,10
1,F,27,41,0,0,0,0,0,0,0,...,10,20,40,0,10,0,0,0,0,10
2,F,26,1,0,0,0,0,0,10,0,...,10,0,50,0,0,0,30,0,0,0
3,M,28,32,0,50,0,0,0,0,0,...,10,10,0,0,0,0,0,0,0,0
4,M,28,18,0,0,0,0,0,0,0,...,0,0,0,0,0,0,10,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12987,F,26,21,0,0,0,0,0,0,0,...,0,10,10,0,0,0,20,0,0,0
12988,F,26,50,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12989,F,27,32,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,0,0,0
12990,F,27,20,0,0,0,0,0,0,0,...,10,0,0,0,0,0,0,0,0,0
12991,F,25,25,0,0,70,0,0,0,0,...,20,0,0,0,20,10,10,0,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12992 entries, 0 to 12991
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   sexo                     12992 non-null  object
 1   edad                     12992 non-null  int64
 2   numero_de_amigos         12992 non-null  int64
 3   basquet                  12992 non-null  int64
 4   futbol_americano         12992 non-null  int64
 5   futbol                   12992 non-null  int64
 6   softbol                  12992 non-null  int64
 7   voleibol                 12992 non-null  int64
 8   natacion                 12992 non-null  int64
 9   animacion                12992 non-null  int64
 10  beisbol                  12992 non-null  int64
 11  tenis                    12992 non-null  int64
 12  deportes                 12992 non-null  int64
 13  tierno                   12992 non-null  int64
 14  danza                    12992 non-null  int64
 15  banda                    12992 non-null  int64
 16  marcha                   12992 non-null  int64
 17  musica                   12992 non-null  int64
 18  rock                     12992 non-null  int64
 19  cabello                  12992 non-null  int64
 20  vestido                  12992 non-null  int64
 21  centro_comercial         12992 non-null  int64
 22  compras                  12992 non-null  int64
 23  ropa                     12992 non-null  int64
 24  nuestra_marca            12992 non-null  int64
 25  marca_de_la_competencia  12992 non-null  int64
 26  bebidas                  12992 non-null  int64
dtypes: int64(26), object(1)
memory usage: 2.7+ MB

In [5]:
df.sexo.unique()

array(['F', 'M', 'NE'], dtype=object)

## Aplicando codificador

In [6]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(categories=[['F', 'M', 'NE']], sparse_output = False)

In [7]:
sexo_codificado = encoder.fit_transform(df[['sexo']])
sexo_codificado

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [8]:
encoded_df = pd.DataFrame(sexo_codificado, columns=encoder.get_feature_names_out(['sexo']))

In [9]:
datos = pd.concat([df, encoded_df], axis=1).drop('sexo', axis=1)
datos

,edad,numero_de_amigos,basquet,futbol_americano,futbol,softbol,voleibol,natacion,animacion,beisbol,...,vestido,centro_comercial,compras,ropa,nuestra_marca,marca_de_la_competencia,bebidas,sexo_F,sexo_M,sexo_NE
0,27,49,0,0,10,0,0,10,0,0,...,0,0,0,0,0,0,10,1.0,0.0,0.0
1,27,41,0,0,0,0,0,0,0,10,...,0,10,0,0,0,0,10,1.0,0.0,0.0
2,26,1,0,0,0,0,0,10,0,0,...,0,0,0,30,0,0,0,1.0,0.0,0.0
3,28,32,0,50,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0.0,1.0,0.0
4,28,18,0,0,0,0,0,0,0,0,...,0,0,0,10,0,0,0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12987,26,21,0,0,0,0,0,0,0,0,...,0,0,0,20,0,0,0,1.0,0.0,0.0
12988,26,50,0,0,0,0,0,0,0,10,...,0,0,0,0,0,0,0,1.0,0.0,0.0
12989,27,32,0,0,0,0,0,0,10,0,...,0,0,0,0,0,0,0,1.0,0.0,0.0
12990,27,20,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1.0,0.0,0.0
12991,25,25,0,0,70,0,0,0,0,0,...,0,20,10,10,0,0,0,1.0,0.0,0.0

In [10]:
import joblib

joblib.dump(encoder, 'encoder.pkl')

['encoder.pkl']

## Desarrollando el modelo

In [11]:
from sklearn.cluster import KMeans

mod_kmeans = KMeans(n_clusters=2, random_state=45)

In [12]:
modelo = mod_kmeans.fit(datos)

# Evaluando el K-means

## Evaluando métricas para diferentes K

## Clase 2.3 - Verificando la silueta por muestras

### Otras visualizaciones

# Evaluación y ajuste de datos

## Verificando las métricas para los nuevos datos

## Creando el mejor modelo

# Analizando las informaciones de cada cluster

## Describiendo cada agrupamiento

# Proyecto Final: Descubre tu Tribu Digital

En este proyecto vas a aplicar lo aprendido en clustering para segmentar usuarios según su estilo de vida y sus intereses.

La base de datos que usamos contiene información sobre deportes, música, ropa y más. A partir de estos datos, vas a descubrir **grupos con perfiles similares** que podrían representar "tribus digitales".

## Objetivo

🎯 **Objetivo:** Ayudar a un equipo de marketing a entender mejor los diferentes perfiles de usuarios para personalizar campañas y productos.

## Seleccionando variables

 ## Visualización

## 🚀 Bonus: Visualiza todo como una app interactiva

Todo este análisis puede convertirse en una **aplicación web** usando Streamlit.
🔗 [Haz clic aquí para probar la app en vivo](https://tu-app.streamlit.app)

La app permite:
- Cambiar la cantidad de clusters
- Elegir qué columnas usar
- Visualizar los grupos en 2D
- Ver el perfil promedio de cada tribu digital